require:
  - rubocop-rails
  - rubocop-rspec
Style/Documentation:
  Enabled: false
Metrics/BlockLength: #ファイルの記述量が長いのを無視
  Exclude:
    - 'config/environments/*.rb'
Metrics/MethodLength: #メソッドが長いのを無視
  Exclude:
    - "db/migrate/*"